name: Bjørn Hamre

permalink: /blog/:year/:month/:day/:title
posts: _posts 

fenced_code_blocks: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
# Use existing pygments syntax highlighting css
    css_class: 'highlight'
    block:
      line_numbers: true
      start_line: 1